//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PricebookGraana
    {
        public double Taskno { get; set; }
        public string Name { get; set; }
        public string Category { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<double> MATERIAL { get; set; }
        public Nullable<double> HR_RATE { get; set; }
        public Nullable<double> TIME { get; set; }
        public Nullable<double> STANDARD { get; set; }
        public Nullable<double> VALUE { get; set; }
        public Nullable<double> MEMBER { get; set; }
        public string Tech_Notes { get; set; }
    }
}
